// server/src/utils/pdfGenerator.js
const pdf = require('html-pdf');
const fs = require('fs');
const path = require('path');
const QRCode = require('qrcode');

// Sample payment data (replace with your actual UPI ID or payment link)
const PAYMENT_LINK = 'upi://pay?pa=yourupiid@bank&pn=TransportBill&am=';

// Function to generate the HTML content for the invoice
const generateHtml = (bill, qrCodeDataUrl) => {
  const date = new Date(bill.date).toLocaleDateString();
  const time = new Date(bill.date).toLocaleTimeString();

  return `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Invoice #${bill.billNumber}</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 0; }
            .invoice-box { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #eee; box-shadow: 0 0 10px rgba(0, 0, 0, .15); font-size: 12px; line-height: 18px; color: #555; }
            .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px; }
            .company-info h2 { color: #333; margin: 0; }
            .invoice-details { text-align: right; }
            .invoice-details h3 { margin: 0; font-size: 16px; color: #333; }
            .customer-info { margin-bottom: 25px; border-top: 1px solid #eee; padding-top: 10px; }
            .item-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .item-table th, .item-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            .item-table th { background-color: #f2f2f2; }
            .total-row td { border-top: 2px solid #333; font-weight: bold; }
            .footer-section { display: flex; justify-content: space-between; margin-top: 40px; }
            .qr-code-box { border: 1px solid #ccc; padding: 10px; text-align: center; }
            .qr-code-box img { width: 100px; height: 100px; }
            .summary { float: right; width: 40%; }
        </style>
    </head>
    <body>
        <div class="invoice-box">
            <div class="header">
                <div class="company-info">
                    <h2>TRANSPORT BILLING SERVICES</h2>
                    <div>123 Transport Hub, Industrial Area, City</div>
                    <div>GSTIN: ABCDE12345Z1A2</div>
                </div>
                <div class="invoice-details">
                    <h3>INVOICE #${bill.billNumber}</h3>
                    <div>Date: ${date}</div>
                    <div>Time: ${time}</div>
                    <div>Generated by: ${bill.staffName} (${bill.createdBy.toString()})</div>
                </div>
            </div>

            <div class="customer-info">
                <strong>Bill To:</strong><br>
                Name: ${bill.customerName}<br>
                Phone: ${bill.customerPhone || 'N/A'}<br>
                GST Number: ${bill.gstNumber}
            </div>

            <table class="item-table">
                <thead>
                    <tr>
                        <th>Description</th>
                        <th>From/To</th>
                        <th>Vehicle No.</th>
                        <th>Rate/Pkg</th>
                        <th>No. of Pkgs</th>
                        <th>Sub Total (₹)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Transport of ${bill.packageCategory}</td>
                        <td>${bill.fromLocation} to ${bill.toLocation}</td>
                        <td>${bill.vehicleNumber}</td>
                        <td>${bill.ratePerPackage.toFixed(2)}</td>
                        <td>${bill.numberOfPackages}</td>
                        <td>${bill.subTotal.toFixed(2)}</td>
                    </tr>
                </tbody>
            </table>

            <div class="summary">
                <table style="width: 100%; margin-top: 20px;">
                    <tr><td style="text-align: right;">Sub Total:</td><td style="width: 30%; text-align: right;">₹ ${bill.subTotal.toFixed(2)}</td></tr>
                    <tr><td style="text-align: right;">GST (${(bill.gstRate * 100).toFixed(0)}%):</td><td style="text-align: right;">₹ ${bill.gstAmount.toFixed(2)}</td></tr>
                    <tr class="total-row"><td style="text-align: right;">TOTAL AMOUNT:</td><td style="text-align: right;">₹ ${bill.totalAmount.toFixed(2)}</td></tr>
                </table>
            </div>
            
            <div style="clear: both;"></div>

            <div class="footer-section">
                <div class="qr-code-box">
                    <p>Scan for Online Payment</p>
                    <img src="${qrCodeDataUrl}" alt="QR Code Payment">
                    <p>Total: ₹ ${bill.totalAmount.toFixed(2)}</p>
                </div>

                <div style="text-align: right; padding-top: 50px;">
                    <p>Signature (Authorized Signatory)</p>
                </div>
            </div>
            <p style="margin-top: 40px; text-align: center; font-size: 10px; color: #999;">This is a system-generated invoice and does not require a physical signature.</p>
        </div>
    </body>
    </html>
  `;
};

// Main function to generate the PDF Buffer
exports.generatePdf = async (bill) => {
  // 1. Generate QR Code Data URL
  const paymentString = `${PAYMENT_LINK}${bill.totalAmount.toFixed(2)}`;
  const qrCodeDataUrl = await QRCode.toDataURL(paymentString, { 
    errorCorrectionLevel: 'H',
    type: 'image/png'
  });

  // 2. Generate HTML content
  const htmlContent = generateHtml(bill, qrCodeDataUrl);

  // 3. Configure PDF options
  const options = {
    format: 'A4',
    orientation: 'portrait',
    border: '10mm',
    type: 'pdf',
    timeout: 30000,
  };

  // 4. Generate PDF
  return new Promise((resolve, reject) => {
    pdf.create(htmlContent, options).toBuffer((err, buffer) => {
      if (err) {
        console.error('PDF Generation Error:', err);
        return reject(err);
      }
      resolve(buffer);
    });
  });
};
